@user-api-minimal_HostAddress = https://localhost:7150

POST {{user-api-minimal_HostAddress}}/users
Content-Type: application/json

  {
    "firstName": "Michael",
    "lastName": "Knight",
    "email": "info@saqaya.com",
    "marketingConsent": false
  }

###

GET {{user-api-minimal_HostAddress}}/users

###
// GET {{user-api-minimal_HostAddress}}/users/{id}
GET {{user-api-minimal_HostAddress}}/users/7B5BLbq/V/lCXO3DUwaKtdeqSO4=

###
