@user-api-minimal_HostAddress = https://localhost:7150

POST {{user-api-minimal_HostAddress}}/user
Content-Type: application/json

  {
    "firstName": "Michael",
    "lastName": "Knight",
    "email": "info@saqaya.com",
    "marketingConsent": false
  }

###

GET {{user-api-minimal_HostAddress}}/user

###
// GET {{user-api-minimal_HostAddress}}/user/{id}
GET {{user-api-minimal_HostAddress}}/user/7B5BLbq/V/lCXO3DUwaKtdeqSO4=

###

GET {{user-api-minimal_HostAddress}}/user/Jwt/demo

###
